resources:
  - name: concourse-pipelines
    type: git
    icon: github
    source:
      uri: git@github.com:vittoriodargenio92/concourse-pipelines.git

jobs:
  - name: configure-self
    plan:
      - get: concourse-pipelines
        trigger: true
      - set_pipeline: concourse-pipelines
        file: concourse-pipelines/parent-pipeline.yaml
  - name: configure-pipelines
    plan:
      - get: concourse-pipelines
        trigger: true
        passed: [configure-self]