resources:
  - name: python-example-git
    type: git
    icon: github
    source:
      uri: https://github.com/vittoriodargenio92/python-example.git


jobs:
  - name: python-example
    plan:
      - get: python-example-git
        trigger: true
      - task: python-example-start
        config:
          platform: linux
          inputs:
            - name: python-example-git
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: [ "-la" ]

#      - task: render-pipelines
#        config:
#          platform: linux
#          image_resource:
#            type: registry-image
#            source: { repository: busybox }
#            source:
#              repository: python
#              tag: 3.8-slim-bullseye
#        run:
#          path: echo
#          args: ["Hello world!"]